### ISSUE TITLE
Sasa dependency

### ISSUE THREAD

**Issue by buptkang** [naasking/uKanren.NET#2]
Why do not you migrate all you Sasa code repo into the github instead of source forge?

**Comment by naasking** [comment]
Sourceforge works fine, so I don't see a specific advantage in doing this at this time. In any case, this isn't the proper place to discuss Sasa. My e-mail is publically available on my profile if you don't want to post to Sasa's forums.

**Comment by buptkang** [comment]
@naasking I am trying to extend your uKanren to add constraining solving ability so as to fit for my research need.

**Comment by naasking** [comment]
I suggest reading about cKanren. It's uKanren extended with constraints.
